CREATE TABLE `companies_list_details` (
  `company_detail_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_company_id` int(10) unsigned NOT NULL,
  `company_detail_name` varchar(45) DEFAULT NULL COMMENT 'Тип реквизита',
  `company_name` varchar(255) DEFAULT NULL COMMENT 'Полное Название',
  `company_person` varchar(255) DEFAULT NULL COMMENT 'Контактное лицо',
  `company_director` varchar(45) DEFAULT NULL COMMENT 'Директор',
  `company_email` varchar(255) DEFAULT NULL COMMENT 'Емаил',
  `company_web` varchar(255) DEFAULT NULL COMMENT 'Сайт',
  `company_phone` varchar(255) DEFAULT NULL COMMENT 'Телефон',
  `company_mobile` varchar(255) DEFAULT NULL COMMENT 'Мобильный телефон',
  `company_address_flat` varchar(10) DEFAULT NULL COMMENT 'Квартира/офис',
  `company_address_building` varchar(10) DEFAULT NULL COMMENT 'Дом/владение/строение',
  `company_address_street` varchar(60) DEFAULT NULL COMMENT 'Улица',
  `company_address_settlement` varchar(30) DEFAULT NULL COMMENT 'Населенный пункт',
  `company_address_district` varchar(30) DEFAULT NULL COMMENT 'Район',
  `company_address_region` varchar(20) DEFAULT NULL COMMENT 'Регион',
  `company_address_zip` varchar(10) DEFAULT NULL COMMENT 'Индекс',
  `company_bank_id` varchar(45) DEFAULT NULL COMMENT 'Банк Код',
  `company_bank_name` varchar(255) DEFAULT NULL COMMENT 'Банк Название',
  `company_bank_account` varchar(45) DEFAULT NULL COMMENT 'Банк Счет',
  `company_bank_corr_account` varchar(45) DEFAULT NULL COMMENT 'Банк Корр. Счет',
  `company_tax_id` varchar(45) DEFAULT NULL COMMENT 'ИНН',
  `company_tax_id2` varchar(45) DEFAULT NULL COMMENT 'КПП',
  `company_code` varchar(45) DEFAULT NULL COMMENT 'ОКПО',
  `company_code_registration` varchar(45) DEFAULT NULL COMMENT 'ОГРН',
  `company_vat_rate` int(11) unsigned DEFAULT NULL COMMENT '% НДС',
  `company_description` text COMMENT 'Дополнительно',
  `company_address` varchar(255) GENERATED ALWAYS AS (concat(`company_address_zip`,', ',`company_address_region`,', ',`company_address_district`,', ',`company_address_settlement`,', ',`company_address_street`,', ',`company_address_building`,', ',`company_address_flat`)) STORED COMMENT 'Адрес',
  PRIMARY KEY (`company_detail_id`),
  KEY `parent_company_id` (`parent_company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
